version: '3.8'

services:
  ray-head:
    build: .
    container_name: ray-head
    command: ["bash", "-c", "ray start --head --port=6379 && tail -f /dev/null"]
    ports:
      - "6379:6379"
    environment:
      - RAY_HEAD_SERVICE_HOST=ray-head
      - RAY_HEAD_SERVICE_PORT=6379
    volumes:
      - .:/app
      - ./results:/app/results
    shm_size: 2gb

  ray-worker:
    build: .
    command: ["bash", "-c", "ray start --address='172.18.0.2:6379' && tail -f /dev/null"]
    environment:
      - RAY_HEAD_SERVICE_HOST=ray-head
      - RAY_HEAD_SERVICE_PORT=6379
    depends_on:
      - ray-head
    volumes:
      - .:/app
    shm_size: 2gb
